# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

            # When using the HTTP Cache, ESI allows to render page fragments separately
            # and with different cache configurations for each fragment
            # https://symfony.com/doc/current/http_cache/esi.html
    esi: true
    fragments: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
