#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#toutes les routes du fichier routes/front.yaml auront pour préfixe _locale(fr,en,es)
front:
    resource: 'routes/front.yaml'
    prefix:   /{_locale}
    requirements:
        _locale: '%app_locales%'

admin:
    resource: 'routes/admin.yaml'
    prefix:   /{_locale}
    requirements:
        _locale: '%app_locales%'

homepage:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'
